name: Auto Build

on:
  workflow_dispatch:
    inputs:
      forceBuild:
        description: 'Force build without checking for existing build'
        required: false
        type: boolean
  schedule:
    # Midnight UTC build
    - cron: '0 0 * * *'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  # Prepare step, check if we need to actually build
  prepare:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.check.outputs.VERSION }}
      VERSION_TAG: ${{ steps.check.outputs.VERSION_TAG }}
      SHOULD_RUN: ${{ steps.check.outputs.SHOULD_RUN}}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Setup Python
        uses: actions/setup-python@b64ffcaf5b410884ad320a9cfac8866006a109aa # v4.8.0
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Requirements
        run: |
          pip3 install -r requirements.txt

      - name: Run Check
        id: check
        env:
          FORCE_BUILD: ${{ github.event.inputs.forceBuild }}
        run: |
          python3 scripts/000_precheck.py

  # Only continue if prepare step passes
  call-non-root:
    needs: [prepare]
    if: needs.prepare.outputs.SHOULD_RUN == 'true'
    uses: ./.github/workflows/base.yml
    with:
      excluded-module: "custom-branding-icon-afn-red,custom-branding-icon-red,custom-branding-icon-blue,custom-branding-icon-revancify-blue"
      included-module: "custom-branding-name,microg-support,theme,materialyou"
      filename: "revanced"
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  call-root:
    needs: [prepare]
    if: needs.prepare.outputs.SHOULD_RUN == 'true'
    uses: ./.github/workflows/base.yml
    with:
      excluded-module: "custom-branding-icon-afn-red,custom-branding-icon-red,custom-branding-icon-blue,custom-branding-icon-revancify-blue,custom-branding-name,microg-support"
      included-module: "theme,materialyou"
      filename: "revanced-root"
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  # Only run if both call steps pass
  publish:
    needs: [prepare, call-non-root, call-root]
    if: success()

    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Setup Python
        uses: actions/setup-python@b64ffcaf5b410884ad320a9cfac8866006a109aa # v4.8.0
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Requirements
        run: |
          pip3 install -r requirements.txt

      - name: Download Root
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: ${{ needs.call-root.outputs.apk }}
          path: ${{ needs.call-root.outputs.apk }}

      - name: Download Non-Root
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: ${{ needs.call-non-root.outputs.apk }}
          path: ${{ needs.call-non-root.outputs.apk }}

      - name: Prepare
        run: |
          python3 scripts/005_make_release.py
        env:
          GITHUB_GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          VERSION_BUILD: ${{ needs.prepare.outputs.VERSION }}
          OPTIONS_ROOT: ${{ needs.call-root.outputs.options }}
          OPTIONS_NON_ROOT: ${{ needs.call-non-root.outputs.options }}
          FILENAME_ROOT: ${{ needs.call-root.outputs.apk }}
          FILENAME_NON_ROOT: ${{ needs.call-non-root.outputs.apk }}

      - name: Summary
        run: |
          echo "# Build Summary" > $GITHUB_STEP_SUMMARY
          cat GENERATED_RELEASE_NOTES.md >> $GITHUB_STEP_SUMMARY

      - name: Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          body_path: "GENERATED_RELEASE_NOTES.md"
          tag_name: "v${{ needs.prepare.outputs.VERSION_TAG }}"
          name: "ReVanced Auto Build v${{ needs.prepare.outputs.VERSION }}"
          token: ${{ secrets.RELEASE_TOKEN }}
          files: |
            ${{ needs.call-non-root.outputs.apk }}
            ${{ needs.call-root.outputs.apk }}
