# this script will be called on auto-build.yml

on:
  workflow_call:
    inputs:
      filename:
        required: true
        description: "The final filename you wanted"
        type: string
      excluded-module:
        required: false
        description: "Module that you don't want to include when building, separated by comma"
        type: string
      included-module:
        required: false
        description: "Module that you want to force include when building, separated by comma"
        type: string
      base-repository:
        required: false
        description: "The default organization that will be used to make the build"
        default: "inotia00"
        type: string
    secrets:
      github-token:
        required: true
        description: "Github token to access repository and bypass limitation"
    outputs:
      options:
        description: "The options that used to build the APK"
        value: ${{ jobs.build.outputs.build-options }}
      apk:
        description: "The final APK that will be uploaded"
        value: ${{ jobs.build.outputs.final-apk }}

env:
  BASE_REPOSITORY: ${{ inputs.base-repository }}
  EXCLUDED_MODULE: ${{ inputs.excluded-module }}
  INCLUDED_MODULE: ${{ inputs.included-module }}
  GITHUB_TOKEN: ${{ secrets.github-token }}
  FILENAME: ${{ inputs.filename }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-options: ${{ steps.build-thing.outputs.BUILD_OPTIONS }}
      final-apk: ${{ steps.build-thing.outputs.FINAL_APK }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.azul.com:443
            cdn.azul.com:443
            api.github.com:443
            files.pythonhosted.org:443
            github.com:443
            objects.githubusercontent.com:443
            pypi.org:443
            raw.githubusercontent.com:443
            *.apkmirror.com:443
            *.actions.githubusercontent.com:443

      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Setup JDK
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          java-version: '17'
          distribution: 'zulu'
      
      - name: Setup Python
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Requirements
        run: |
          pip3 install -r requirements.txt

      - name: Get Latest Compatible Version
        id: latest-compat
        run: |
          python3 scripts/001_fetch.py

      - name: Get APKs
        run: |
          python3 scripts/002_apks_download.py ${{ steps.latest-compat.outputs.version }}

      - name: Get Tooling
        run: |
          python3 scripts/003_assets_download.py

      - name: Run build
        id: build-thing
        run: |
          python3 scripts/004_build.py ${{ steps.latest-compat.outputs.version }}
          mv revanced.apk "${FILENAME}-${{ steps.latest-compat.outputs.version }}.apk"
          # Read the options.json and put it to output
          echo "FINAL_APK=${FILENAME}-${{ steps.latest-compat.outputs.version }}.apk" >> $GITHUB_OUTPUT

      - name: Upload APK
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: ${{ steps.build-thing.outputs.FINAL_APK }}
          path: ${{ steps.build-thing.outputs.FINAL_APK }}
